# Render.com deployment configuration
services:
  - type: web
    name: deepdetect-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
